coverage:
  range: 70..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 80
    patch:
      default:
        target: auto
        threshold: 1%

codecov:
  require_ci_to_pass: yes
