version: "3"

services:
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    image: postgres:12.6
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aecworks_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres

volumes:
  postgres_data:

networks:
  default:
    external:
      name: aecworks-network
