# Generated by Django 2.2.12 on 2020-08-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_avatar_as_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='avatar_url',
        ),
    ]
