# Generated by Django 2.2.13 on 2020-09-23 05:04

from django.db import migrations

# MOVED
# editor_permissions = [
#     "add_companyrevision",
#     "change_company",
#     "apply_companyrevision",
#     "add_company",
#     "add_hashtag",
#     "delete_company",
# ]
# group_settings = {
#     "editors": editor_permissions,
# }


def up(apps, schema_editor):
    ...


def down(apps, schema_editor):
    ...


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_image_create_at"),
    ]

    operations = [migrations.RunPython(up, down)]
