# Generated by Django 2.2.13 on 2020-10-09 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_rename_image_asset"),
        ("users", "0008_add_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="images.ImageAsset",
            ),
        ),
    ]
