# Generated by Django 2.2.13 on 2020-10-06 07:07

from django.db import migrations, models
import django.db.models.deletion

from api.images.service import create_image_file_from_url


def up(apps, schema_editor):
    """ Create new ImageAsset and set to Avatar Url """

    Profile = apps.get_model("users", "Profile")
    ImageAsset = apps.get_model("images", "ImageAsset")
    for profile in Profile.objects.all():
        if profile.avatar_url:
            img_file = create_image_file_from_url(profile.avatar_url)
            img = ImageAsset.objects.create(file=img_file, created_by=profile)
            profile.avatar = img
            profile.save()


def down(apps, schema_editor):
    """ Set Url from ImageAsset Url """
    Profile = apps.get_model("users", "Profile")
    for profile in Profile.objects.all():
        if profile.avatar:
            profile.avatar_url = profile.avatar.file.url
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_rename_image_asset"),
        ("users", "0008_add_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_img",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="images.ImageAsset",
            ),
        ),
        migrations.RunPython(up, down),
        migrations.RemoveField(model_name="profile", name="avatar_url",),
    ]
