# Generated by Django 2.2.13 on 2020-10-09 03:53

from django.db import migrations, models


def up(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    for profile in Profile.objects.all():
        if profile.github_url:
            profile.github = profile.github_url.split("/")[-1]
            profile.save()


def down(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    for profile in Profile.objects.all():
        if profile.github:
            profile.github_url = f"https://api.github.com/users/{profile.github}"
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_add_image_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.RunPython(up, down),
        migrations.RemoveField(model_name="profile", name="github_url",),
    ]
