# Generated by Django 2.2.13 on 2020-10-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_github_user_instead_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
    ]
