# Generated by Django 2.2.13 on 2020-10-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_github'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar_img',
            new_name='avatar',
        ),
    ]
