# Generated by Django 2.2.20 on 2021-04-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_image_url_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="provider",
            field=models.CharField(
                choices=[
                    ("SIGN_UP", "registration"),
                    ("GITHUB", "github"),
                    ("LINKEDIN", "linkedin"),
                ],
                default="SIGN_UP",
                max_length=16,
            ),
        ),
    ]
