# Generated by Django 2.2.12 on 2020-05-19 04:48

from django.db import migrations, models

import api.common.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(api.common.mixins.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('location', models.CharField(default='', max_length=64)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=15, null=True)),
                ('crunchbase_id', models.CharField(blank=True, max_length=128, null=True)),
                ('employee_count', models.CharField(blank=True, choices=[('TEN', '1 - 10'), ('FIFTY', '11 - 50'), ('TWO_HUNDRED', '51 - 200'), ('FIVE_HUNDRED', '201 - 500'), ('ONE_THOUSAND', '501 - 1000'), ('FIVE_THOUSAND', '1001 - 5000'), ('TEN_THOUSAND', '5001 - 10,000')], default='TEN', max_length=32, null=True)),
                ('logo', models.ImageField(blank=True, default='default_logo.png', upload_to='logos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
            bases=(api.common.mixins.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
            ],
            bases=(api.common.mixins.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(api.common.mixins.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(api.common.mixins.ReprMixin, models.Model),
        ),
    ]
