# Generated by Django 2.2.12 on 2020-05-11 05:55

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clappers',
            field=models.ManyToManyField(related_name='clapped_posts', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(related_name='posts', to='community.Hashtag'),
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='root_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community.Comment'),
        ),
        migrations.AddField(
            model_name='company',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='company',
            name='clappers',
            field=models.ManyToManyField(related_name='clapped_companies', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='company',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='company',
            name='hashtags',
            field=models.ManyToManyField(related_name='companies', to='community.Hashtag'),
        ),
        migrations.AddField(
            model_name='company',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replaced', to='community.Company'),
        ),
        migrations.AddField(
            model_name='company',
            name='revision_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='community.Company'),
        ),
        migrations.AddField(
            model_name='company',
            name='root_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='clappers',
            field=models.ManyToManyField(related_name='clapped_comments', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='users.Profile'),
        ),
    ]
