# Generated by Django 2.2.12 on 2020-05-28 06:16

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_auto_20200519_0448"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name"
            ),
        ),
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.SlugField(max_length=32, unique=True),
        ),
        migrations.RenameField(model_name="hashtag", old_name="name", new_name="slug",),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title"
            ),
        ),
    ]
