# Generated by Django 2.2.12 on 2020-05-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200511_0555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'comapanies'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='clappers',
            field=models.ManyToManyField(blank=True, related_name='clapped_comments', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='clappers',
            field=models.ManyToManyField(blank=True, related_name='clapped_companies', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='companies', to='community.Hashtag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='clappers',
            field=models.ManyToManyField(blank=True, related_name='clapped_posts', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='community.Hashtag'),
        ),
    ]
