# Generated by Django 2.2.12 on 2020-05-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200518_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comment_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='community.CommentThread'),
        ),
    ]
