# Generated by Django 2.2.12 on 2020-05-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20200511_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
