# Generated by Django 2.2.12 on 2020-05-19 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20200518_0745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentThread',
            new_name='Thread',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='comment_thread',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='comment_thread',
            new_name='thread',
        ),
    ]
