# Generated by Django 2.2.12 on 2020-08-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_hot_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='editor',
            new_name='profile',
        ),
    ]
