# Generated by Django 2.2.12 on 2020-05-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20200511_0618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AddField(
            model_name='post',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='posts', to='community.Company'),
        ),
    ]
