# Generated by Django 2.2.12 on 2020-08-12 05:08

import django.db.models.deletion
from django.db import migrations, models

import api.common.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_slug'),
        ('community', '0006_add_cover_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employee_count',
        ),
        migrations.RemoveField(
            model_name='company',
            name='founded_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='company',
            name='replaced_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='revision_of',
        ),
        migrations.AddField(
            model_name='company',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='additions', to='users.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CompanyRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('location', models.CharField(default='', max_length=64)),
                ('twitter_handle', models.CharField(blank=True, max_length=15, null=True)),
                ('crunchbase_id', models.CharField(blank=True, max_length=128, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers')),
                ('applied', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='community.Company')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='users.Profile')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, api.common.mixins.ReprMixin),
        ),
    ]
