# Generated by Django 2.2.12 on 2020-08-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_company_revision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='added_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='companyrevision',
            old_name='edited_by',
            new_name='created_by',
        ),
    ]
