# Generated by Django 2.2.12 on 2020-05-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20200512_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='thread',
        ),
        migrations.AddField(
            model_name='commentthread',
            name='comments',
            field=models.ManyToManyField(related_name='thread', to='community.Comment'),
        ),
    ]
