# Generated by Django 2.2.12 on 2020-05-12 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20200512_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentthread',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.CommentThread'),
        ),
    ]
