# Generated by Django 2.2.12 on 2020-08-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrevision',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='_companyrevision_hashtags_+', to='community.Hashtag'),
        ),
    ]
