# Generated by Django 2.2.12 on 2020-05-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20200512_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default='', max_length=64),
        ),
    ]
