# Generated by Django 2.2.12 on 2020-08-24 07:26

from django.db import migrations, models

import api.common.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tmp')),
            ],
            bases=(api.common.mixins.ReprMixin, models.Model),
        ),
    ]
