# Generated by Django 2.2.12 on 2020-05-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='public/default_logo.png', null=True, upload_to='logos'),
        ),
    ]
