# Generated by Django 2.2.12 on 2020-05-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_auto_20200512_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='public/default_logo.png', upload_to='logos'),
        ),
    ]
