# Generated by Django 2.2.12 on 2020-08-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_new_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryImage',
        ),
    ]
