# Generated by Django 2.2.12 on 2020-08-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_remove_temp_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
