# Generated by Django 2.2.12 on 2020-08-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_split_image_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.CharField(choices=[('FIRST_POST', 'First Post')], default='', max_length=32),
        ),
    ]
