# Generated by Django 2.2.12 on 2020-09-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_add_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='slug',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
