# Generated by Django 2.2.12 on 2020-09-14 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_hashtag_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='last_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community.CompanyRevision'),
        ),
        migrations.AlterField(
            model_name='companyrevision',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='community.Company'),
        ),
    ]
