# Generated by Django 2.2.13 on 2020-09-15 07:37

import api.common.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_image_create_at'),
        ('community', '0018_cascade_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='community.Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='users.Profile')),
            ],
            bases=(api.common.mixins.ReprMixin, models.Model),
        ),
    ]
