# Generated by Django 2.2.12 on 2020-09-18 06:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_add_opengraph_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='opengraph_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
