# Generated by Django 2.2.12 on 2020-09-17 07:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='opengraph_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
