# Generated by Django 2.2.13 on 2020-09-23 04:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_null_opengraph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('can_apply_revision', 'Can Apply Revision')], 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='article',
            name='opengraph_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
