# Generated by Django 2.2.13 on 2020-10-04 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_rename_image_asset'),
        ('community', '0021_add_apply_revision_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='images.ImageAsset'),
        ),
    ]
