# Generated by Django 2.2.13 on 2020-10-06 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_rename_image_asset'),
        ('community', '0022_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(related_name='posts', to='images.ImageAsset'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_covers', to='images.ImageAsset'),
        ),
    ]
