# Generated by Django 2.2.13 on 2020-10-07 04:55

from django.db import migrations, models
import django.db.models.deletion

from api.images.service import create_image_file_from_url


def up(apps, schema_editor):
    """ Create new ImageAsset and set to Avatar Url """

    Company = apps.get_model("community", "Company")
    CompanyRevision = apps.get_model("community", "CompanyRevision")
    ImageAsset = apps.get_model("images", "ImageAsset")
    for company in list(Company.objects.all()) + list(CompanyRevision.objects.all()):
        if company.logo_url:
            img_file = create_image_file_from_url(company.logo_url)
            img = ImageAsset.objects.create(file=img_file)
            company.logo = img
            company.save()
        if company.cover_url:
            img_file = create_image_file_from_url(company.cover_url)
            img = ImageAsset.objects.create(file=img_file)
            company.cover = img
            company.save()


def down(apps, schema_editor):
    """ Set Url from ImageAsset Url """
    Company = apps.get_model("community", "Company")
    CompanyRevision = apps.get_model("community", "CompanyRevision")
    for company in list(Company.objects.all()) + list(CompanyRevision.objects.all()):
        if company.logo:
            company.logo_url = company.logo.file.url
            company.save()
        if company.cover:
            company.logo_url = company.logo.file.url
            company.save()


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_rename_image_asset"),
        ("community", "0023_post_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.ImageAsset",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.ImageAsset",
            ),
        ),
        migrations.AddField(
            model_name="companyrevision",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.ImageAsset",
            ),
        ),
        migrations.AddField(
            model_name="companyrevision",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.ImageAsset",
            ),
        ),
        migrations.RenameField(
            model_name="company", old_name="twitter_handle", new_name="twitter",
        ),
        migrations.RenameField(
            model_name="companyrevision", old_name="twitter_handle", new_name="twitter",
        ),
        migrations.RunPython(up, down),
        migrations.RemoveField(model_name="company", name="cover_url",),
        migrations.RemoveField(model_name="company", name="logo_url",),
        migrations.RemoveField(model_name="companyrevision", name="cover_url",),
        migrations.RemoveField(model_name="companyrevision", name="logo_url",),
    ]
