# Generated by Django 2.2.13 on 2020-10-07 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0024_image_asset_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover_img',
            new_name='cover',
        ),
    ]
