# Generated by Django 2.2.20 on 2021-04-15 06:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0029_comment_replies_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='opengraph_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
