# Generated by Django 2.2.20 on 2021-04-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0031_remove_nested_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='banner',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
