# Generated by Django 2.2.20 on 2021-04-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0032_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
