# Generated by Django 2.2.20 on 2021-04-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0033_thread_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='clap_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(db_index=True, default='Somewhere', max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='companyrevision',
            name='location',
            field=models.CharField(db_index=True, default='Somewhere', max_length=64),
        ),
        migrations.AlterField(
            model_name='companyrevision',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
