# Generated by Django 2.2.20 on 2021-04-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0034_index_for_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
