# Generated by Django 2.2.20 on 2021-04-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0035_hashtags_updated_'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrevision',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
