# Generated by Django 2.2.20 on 2021-04-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0035_hashtags_updated_'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=32),
        ),
    ]
