# Generated by Django 2.2.20 on 2021-04-29 21:32

from django.db import migrations, models, transaction

# Generated by Django 2.2.20 on 2021-04-30 06:29


def up(apps, schema_editor):

    Company = apps.get_model("community", "Company")
    CompanyRevision = apps.get_model("community", "CompanyRevision")

    for co in Company.objects.all():

        if not co.current_revision:
            print(f"Company '{co}' does not have a current revision")

            last_rev = CompanyRevision.objects.filter(company=co).last()

            with transaction.atomic():

                if last_rev:
                    co.current_revision = last_rev
                    co.save()
                    print("set revision to last")

                else:
                    print(f"no revision available for: {co}")

                    rev = CompanyRevision.objects.create(
                        company=co,
                        created_by=co.created_by,
                        name=co.name,
                        twitter=co.twitter,
                        description=co.description,
                        location=co.location,
                        website=co.website,
                        crunchbase_id=co.crunchbase_id,
                        logo=co.logo,
                        cover=co.cover,
                    )
                    rev.hashtags.set(co.hashtags.all())
                    co.current_revision = rev
                    co.save()
                    print("revision created")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("community", "0037_current_revision_rename"),
    ]

    operations = [
        migrations.RunPython(up, migrations.RunPython.noop),
        migrations.RemoveField(model_name="company", name="banner",),
        migrations.RemoveField(model_name="company", name="cover",),
        migrations.RemoveField(model_name="company", name="crunchbase_id",),
        migrations.RemoveField(model_name="company", name="description",),
        migrations.RemoveField(model_name="company", name="hashtags",),
        migrations.RemoveField(model_name="company", name="location",),
        migrations.RemoveField(model_name="company", name="logo",),
        migrations.RemoveField(model_name="company", name="name",),
        migrations.RemoveField(model_name="company", name="twitter",),
        migrations.RemoveField(model_name="company", name="website",),
        migrations.RemoveField(model_name="post", name="companies",),
        migrations.AddField(
            model_name="companyrevision",
            name="banner",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
