# Generated by Django 2.2.20 on 2021-04-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0038_simplify_revision_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrevision',
            name='crunchbase_id',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='companyrevision',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
