# Generated by Django 2.2.20 on 2021-04-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0040_twitter_default_string_nonnullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyrevision',
            name='applied',
        ),
    ]
