# Generated by Django 2.2.20 on 2021-04-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0041_remove_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('UNMODERATED', 'Unmoderated'), ('REJECTED', 'Rejected'), ('REVIEWED', 'Reviewed'), ('FLAGGED', 'Flagged')], default='UNMODERATED', max_length=32),
        ),
    ]
