# Generated by Django 2.2.20 on 2021-04-30 05:02

import api.common.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0012_fix_choices'),
        ('community', '0042_update_moderation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('UNMODERATED', 'Unmoderated'), ('REJECTED', 'Rejected'), ('REVIEWED', 'Reviewed'), ('FLAGGED', 'Flagged')], default='UNMODERATED', max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_actions', to='users.Profile')),
            ],
            bases=(api.common.mixins.ReprMixin, models.Model),
        ),
    ]
