# Generated by Django 2.2.20 on 2021-04-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0043_moderation_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrevision',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='revisions', to='community.Hashtag'),
        ),
    ]
