# Generated by Django 2.2.20 on 2021-04-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0044_hashtag_revisions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
