# Generated by Django 2.2.20 on 2021-04-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0045_remove_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='community.CompanyRevision'),
        ),
    ]
