# Generated by Django 2.2.20 on 2021-05-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0046_protect_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='current_revision',
        ),
    ]
