# Generated by Django 2.2.20 on 2021-05-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0047_remove_current_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='community.CompanyRevision'),
        ),
    ]
