# Generated by Django 2.2.20 on 2021-05-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0048_one_to_one_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrevision',
            name='status',
            field=models.CharField(choices=[('UNMODERATED', 'Unmoderated'), ('REJECTED', 'Rejected'), ('REVIEWED', 'Reviewed'), ('FLAGGED', 'Flagged')], default='UNMODERATED', max_length=32),
        ),
    ]
