# Generated by Django 2.2.20 on 2021-05-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0050_remove_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('UNMODERATED', 'Unmoderated'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('APPLIED', 'Applied')], default='UNMODERATED', max_length=32),
        ),
        migrations.AlterField(
            model_name='companyrevision',
            name='status',
            field=models.CharField(choices=[('UNMODERATED', 'Unmoderated'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('APPLIED', 'Applied')], default='UNMODERATED', max_length=32),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='status',
            field=models.CharField(choices=[('UNMODERATED', 'Unmoderated'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('APPLIED', 'Applied')], default='UNMODERATED', max_length=32),
        ),
    ]
