# Generated by Django 2.2.20 on 2021-05-02 16:17

import api.common.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_fix_choices'),
        ('community', '0051_moderation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('UNMODERATED', 'Unmoderated'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged')], default='UNMODERATED', max_length=32),
        ),
        migrations.AlterField(
            model_name='companyrevision',
            name='status',
            field=models.CharField(choices=[('UNMODERATED', 'Unmoderated'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged')], default='UNMODERATED', max_length=32),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='status',
            field=models.CharField(choices=[('UNMODERATED', 'Unmoderated'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged')], default='UNMODERATED', max_length=32),
        ),
        migrations.CreateModel(
            name='CompanyRevisionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_history', to='users.Profile')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='community.CompanyRevision')),
            ],
            bases=(api.common.mixins.ReprMixin, models.Model),
        ),
    ]
