# Generated by Django 2.2.20 on 2021-05-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0052_revision_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyrevisionhistory',
            options={'verbose_name_plural': 'company revisions history'},
        ),
    ]
