# Generated by Django 2.2.20 on 2021-05-03 05:37

from django.db import migrations


def up(apps, schema_editor):
    Company = apps.get_model("community", "Company")
    CompanyRevision = apps.get_model("community", "CompanyRevision")

    for co in Company.objects.all():

        if not co.current_revision:
            print(f"Company '{co}' does not have a current revision")

            last_rev = CompanyRevision.objects.filter(company=co).last()
            if last_rev:
                co.current_revision = last_rev
                co.save()
                print("set revision to last")


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0053_plural_rename"),
    ]

    operations = [migrations.RunPython(up, migrations.RunPython.noop)]
