# Generated by Django 2.2.20 on 2021-05-03 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0054_set_current_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrevision',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='images.ImageAsset'),
        ),
        migrations.AlterField(
            model_name='companyrevision',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='images.ImageAsset'),
        ),
    ]
