#!/bin/bash

set -e
source ./scripts/console.sh

info "pre-commit hook ✨ "

breakpoint=$(git grep breakpoint -- '*.py')
if [ -n "$breakpoint" ]; then
    error "Please remove breakpoint before commiting ❌ "
    info "${breakpoint}"
    exit 1
fi

info "Done"
