# Generated by Django 2.2.12 on 2020-08-25 06:49

import api.images.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=functools.partial(
                            api.images.utils.generate_image_path_partial,
                            *("images",),
                            **{}
                        )
                    ),
                ),
            ],
        ),
    ]
