# Generated by Django 2.2.12 on 2020-08-28 07:05

import api.images.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_split_image_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=functools.partial(api.images.utils._generate_filename, *('images',), **{})),
        ),
    ]
