# Generated by Django 2.2.12 on 2020-08-28 07:05

import functools
from pathlib import Path
from uuid import uuid4

from django.db import migrations, models


def _generate_filename(path, instance, filename):
    random_filename = f"{uuid4().hex}{Path(filename).suffix}"
    return Path(path) / random_filename


generate_image_path_partial = functools.partial(_generate_filename, "images")


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_split_image_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                upload_to=functools.partial(_generate_filename, *("images",), **{})
            ),
        ),
    ]
