# Generated by Django 2.2.12 on 2020-08-29 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_profile_avatar_as_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 29, 8, 25, 59, 312778, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
