# Generated by Django 2.2.12 on 2020-08-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_add_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploaded_by',
            new_name='created_by',
        ),
    ]
