# Generated by Django 2.2.13 on 2020-10-04 07:52

import api.common.mixins
import api.images.utils
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_groups'),
        ('images', '0006_image_created_by_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(height_field='height', upload_to=functools.partial(api.images.utils._generate_filename, *('images',), **{}), width_field='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images_files', to='users.Profile')),
            ],
            bases=(api.common.mixins.ReprMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
