# Generated by Django 2.2.13 on 2020-10-04 08:28
import functools
from django.db import migrations, models

from uuid import uuid4
from pathlib import Path
from functools import partial


def _generate_filename(path, instance, filename):
    random_filename = f"{uuid4().hex}{Path(filename).suffix}"
    return Path(path) / random_filename


generate_image_path_partial = partial(_generate_filename, "images")


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_image_created_by_null"),
    ]

    operations = [
        migrations.RenameModel("Image", "ImageAsset"),
        migrations.AddField(
            model_name="imageasset",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageasset",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="imageasset",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="images_files",
                to="users.Profile",
            ),
        ),
        migrations.AlterField(
            model_name="imageasset",
            name="image",
            field=models.ImageField(
                height_field="height",
                upload_to=functools.partial(_generate_filename, *("images",), **{}),
                width_field="width",
            ),
        ),
        migrations.RenameField(
            model_name="imageasset", old_name="image", new_name="file",
        ),
    ]
